# file: tasks/main.yml

---
- name: common | aptitude install python-software-properties
  apt: pkg=python-software-properties state=present

- name: common | apt add repositories apt_repositories
  apt_repository: repo={{ item }} state=present
  with_items: discourse.common.apt_repositories

- name: common | aptitude upgrade
  apt: update_cache=yes upgrade=yes

- name: common | aptitude install apt_packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: discourse.common.apt_packages

- name: common | create the Discourse directories
  file: name={{ item.name }} state=directory owner={{ item.owner }} group={{ item.group }}
  with_items: discourse.common.directories

- name: common | easy_install pip
  easy_install: name=pip

- name: common | pip install python_packages.requirements
  pip: name={{ item }} state=present
  with_items: discourse.python_packages.requirements

- name: common | createuser discourse
  postgresql_user: name=discourse state=present
  sudo: yes
  sudo_user: postgres

- name: common | install rvm
  shell: "curl -s -S -L https://get.rvm.io | bash -s stable"
