# file: tasks/main.yml

---
- name: common | aptitude install python-software-properties
  apt: pkg=python-software-properties state=present

- name: common | apt add repositories apt_repositories
  apt_repository: repo={{ item }} state=present
  with_items: discourse.common.apt_repos

- name: common | aptitude upgrade
  apt: update_cache=yes upgrade=yes

- name: common | aptitude install apt_packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: discourse.common.apt_packages

- name: common | adduser users
  user: name={{ item.name }} password={{ item.password_hash }} shell={{ item.shell }}
  sudo: yes
  sudo_user: root
  with_items: discourse.users.users

- name: common | create the Discourse directories
  file: name={{ item }} state=directory
  sudo: yes
  sudo_user: discourse
  with_items: discourse.common.directories
