# file: tasks/main.yml

---
- name: users | adduser users
  user: name={{ item.name }} password={{ item.password_hash }} shell={{ item.shell }}
  become: yes
  become_user: root
  loop: discourse.users.users
