# file: tasks/main.yml

---
- name: users | adduser users
  user: name={{ item.name }} password={{ item.password_hash }} shell={{ item.shell }}
  sudo: yes
  sudo_user: root
  with_items: discourse.users.users
